create or replace PROCEDURE UPDATE_SEGMENTED_FIELD(OBJECTID NUMBER, FIELD VARCHAR2, VALUE_NUME NUMBER, VALUE_TEXT VARCHAR2, VALUE_DATE DATE)
AS
  sql_stmt VARCHAR2(255);
BEGIN
  
  sql_stmt := 'UPDATE HPMS_SEGMENTED SET ' || FIELD || ' = :1 WHERE OBJECTID = :2';
  
  -- Check if value of the field is a string
  IF FIELD = 'ROUTE_ID' or FIELD = 'COMMENTS' or FIELD = 'ALTERNATIVE_ROUTE_NAME' or FIELD = 'WIDENING_OBSTACLE' THEN
    EXECUTE IMMEDIATE sql_stmt USING VALUE_TEXT, OBJECTID;

  ELSIF FIELD = 'IRI_DATE' or FIELD = 'YEAR_LAST_IMPROV' or FIELD = 'YEAR_LAST_CONSTRUCTION' THEN
    EXECUTE IMMEDIATE sql_stmt USING VALUE_DATE, OBJECTID;

  ELSE
    EXECUTE IMMEDIATE sql_stmt USING VALUE_NUME, OBJECTID;

  END IF;

END;